<?php 

namespace Savv\Services;

class CacheClearService 
{
    /**
     * Recursively clear all subdirectories and contents inside a path.
     */
    public static function clearDirectory(string $dirPath, bool $removeTargetFolder = false): void {
        if (!is_dir($dirPath)) {
            return;
        }

        $files = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dirPath, \RecursiveDirectoryIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($files as $fileinfo) {
            $todo = ($fileinfo->isDir() ? 'rmdir' : 'unlink');
            @$todo($fileinfo->getRealPath());
        }

        if ($removeTargetFolder) {
            @rmdir($dirPath);
        }
    }

    /**
     * Remove a targeted file path layout resource with immediate log terminal prints.
     */
    public static  function deleteFile(string $filePath): void {
        if (file_exists($filePath)) {
            if (@unlink($filePath)) {
                echo "\e[32mDeleted cache file:\e[0m " . str_replace(ROOT_PATH, '.', $filePath) . "\n";
            } else {
                echo "\e[31mError: Failed to unlink file at:\e[0m {$filePath}\n";
            }
        } else {
            echo "Cache resource file not found, skipping: " . str_replace(ROOT_PATH, '.', $filePath) . "\n";
        }
    }

    /**
     * Open up internal cached array elements, unsets targeted pattern string, and saves output back down.
     */
    public static function removeRouteFromCache(string $routesCacheFile, string $targetRouteSlug): void {
        if (!file_exists($routesCacheFile)) {
            echo "Compiled routing snapshot cache file does not exist.\n";
            return;
        }

        $routes = include $routesCacheFile;
        if (!is_array($routes)) {
            echo "\e[31mError: Cache target is not a valid map index array matrix.\e[0m\n";
            return;
        }

        $initialCount = count($routes);
        
        // Scan inside structural mappings to identify targeting match loops
        foreach ($routes as $index => $routeMeta) {
            $uriPattern = $routeMeta['uri'] ?? '';
            $nameField  = $routeMeta['name'] ?? '';

            // Looks for matches against absolute URI patterns or customized friendly alias tags
            if (str_contains($uriPattern, $targetRouteSlug) || $nameField === $targetRouteSlug) {
                unset($routes[$index]);
            }
        }

        // Re-index array indices to maintain standard numeric array order (0, 1, 2...)
        $routes = array_values($routes);

        if (count($routes) === $initialCount) {
            echo "No matching active cache records found for route identifier: '{$targetRouteSlug}'\n";
            return;
        }

        // Convert data matrix block back to a double-quote safe cache format block
        $exported = var_export($routes, true);
        $exportedWithDoubleQuotes = preg_replace_callback("/'([^'\\\\]*(?:\\\\.[^'\\\\]*)*)'/", function($matches) {
            return '"' . str_replace(["\\'", '"'], ["'", '\\"'], $matches[1]) . '"';
        }, $exported);
        $exportedWithDoubleQuotes = preg_replace("/\"([a-zA-Z0-9_\-]+)\" =>/", "'$1' =>", $exportedWithDoubleQuotes);

        $content = "<?php\n\n// Generated by Savv - " . date('Y-m-d H:i:s') . "\nreturn " . $exportedWithDoubleQuotes . ";";

        if (file_put_contents($routesCacheFile, $content)) {
            $removedCount = $initialCount - count($routes);
            echo "\e[32mSuccessfully removed {$removedCount} cached route rule(s). Routes index updated.\e[0m\n";
        } else {
            echo "\e[31mError updating compiled routing map configurations.\e[0m\n";
        }
    }
}