<?php
namespace Savv\Console\Commands;

use Savv\Utils\Router;

class RouteCache
{
    public function execute($args)
    {
        echo "Starting route compilation...\n";

        // 1. Initialize a fresh Router instance
        $router = Router::getInstance();

        // 2. Load Routes files
        $router->loadRouteFiles();

        // 3. Scan views/ directory for Dynamic Routes
        $this->compileViews($router);

        // 4. Load Redirections
        $this->compileRedirections($router);

        // 5. Load Posts Config Discovery
        $this->compilePosts($router);

        // 6. Save to Storage
        $cachePath = ROOT_PATH . '/storage/framework/routes.php';
        if (!is_dir(dirname($cachePath))) mkdir(dirname($cachePath), 0777, true);

        $exported = var_export($router->getRoutes(), true);
        $content = "<?php\n\n// Generated by Savv - " . date('Y-m-d H:i:s') . "\nreturn " . $exported . ";";
        
        file_put_contents($cachePath, $content);

        echo "Success: Manifest saved to {$cachePath}\n";
    }

    protected function compileViews($router) {
        $viewDir = ROOT_PATH . '/views/pages';
        if (!is_dir($viewDir)) return;

        $files = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($viewDir));
        foreach ($files as $file) {
            if ($file->isDir() || $file->getExtension() !== 'php') continue;

            $relative = str_replace([$viewDir, '.php'], '', $file->getPathname());
            $uri = trim($relative, '/');
            $uri = ($uri === 'index') ? '/' : $uri;

            // Register as a dynamic view route
            $router->get($uri, function() use ($file) {
                require $file->getPathname();
            });
        }
    }

    protected function compileRedirections($router) {
        $redirects = config('redirections') ?? [];
        foreach ($redirects as $slug => $target) {
            $router->get($slug, function() use ($target) {
                $url = is_array($target) ? $target['url'] : $target;
                return response()->redirect($url, is_array($target) ? ($target['status'] ?? 302) : 302);
            });
        }
    }

    protected function compilePosts($router) {
        $posts = config('posts') ?? [];
        foreach ($posts as $slug => $title) {
            // Map /post-slug to the post view
            $router->get("{$slug}", function() use ($slug) {
                // Pass slug to the view via global or request
                $_GET['post_slug'] = $slug; 
                require ROOT_PATH . '/views/pages/post-detail.php';
            });
        }
    }
}